### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by mschae16** [benjaminprat/mod_0_skills#1]
@benjaminprat  - Hi Ben, you performed well enough on this assessment to merit a chance to make some changes that can promote you to `technical ready`. Please make the following updates by EOD Tuesday:

- [x]  Please review and match all data types stipulated in your class attributes with that of the instance attribute values. For example, in the class `ManagementTeam` you have an attribute of `isSommelierCertified` with a data type of `boolean`. However your instance `DelFrisco's` attribute `isSommelierCertified` is set to `"yes"` (string data type). Data types need to match up for both classes and their instances.

- [x]  You have duplicate naming for attributes and method names within the `ManagmentTeam` class. The attribute `isSommelierCertified` is a good name that implies a boolean value. However, to also have a method with the same name is bad practice (and will trigger an error when coding) - why not use the action verb for the method name such as `certifySommelierStatus` or something similar?

- [x] Also, within the `ManagementTeam` class, the `vacationRequest` attribute is set to an array, but the instance values show date strings as well (`"March 31"`, `"June 1"`). Would it be better to set the vacationRequest attribute to an object with key-value pairs?  For example:

```
vacationRequest: { 'March 31': ['Jennifer', 'Tom'], 'June 1': ['Tony'], 'June 2': ['Anne'] }
```

- [x] Please review and update your answer for exercise 9 of part 3, on variable declaration.

>  Write a line of code that removes the first element from the songs array

Please reach out if you any questions on these updates, and let me know once they've been completed. Thanks!

**Comment by benjaminprat** [comment]
Good afternoon Margo-
I have reviewed my work and made changes based on your feedback. I believe I corrected all that was asked. Please let me know if you would like anything else from me. Thank you again!
-Ben

**Comment by mschae16** [comment]
@benjaminprat - Hi Ben, Thanks for making those updates. I'm promoting you to `technical ready` status, congrats! I strongly urge you to keep practicing -- especially with using `true` / `false` for boolean values - I noticed there were still a couple "Yes" / "No" strings thrown around in the `saturdayNightMenu` instance.  Keep up the good work!
